/**
 * transcendenceData.js - hardcoded Transcendence tree content, per class.
 * Same reasoning as talentTreeData.js/awakeningData.js/relicsData.js: fixed
 * game data (transcribed from docs/Transcendence Screenshots/Transcendence
 * tree - Sentinel.txt, verified for position collisions and uncommon-node
 * stat-count correctness), not user-authored, so it lives in code.
 *
 * Node `position` is "col:row" (1-indexed, matches the source doc's own
 * notation - 1:1 is top-left). `type` is 'common' | 'uncommon' | 'glyph' |
 * 'sigil'. `category` is 'offense' | 'defense' | 'glyph' | 'sigil' - stored
 * explicitly per node rather than derived from statKey, since Penetration
 * sits on the offense side of this tree's own Offense/Defense split even
 * though it reads as a "defensive" stat name.
 *
 * `stats` is empty for glyph/sigil nodes (no bonus stat - glyphs are inert
 * placeholders matching their in-game "SOON" badge; sigils grant an
 * undefined "special effect", not a stat). Common nodes always have exactly
 * 1 stat entry, uncommon always exactly 2 - both invariants are enforced by
 * the generator script this file was produced from, not re-checked at runtime.
 */

export const TRANSCENDENCE_START_POSITION = '14:25';

export const TRANSCENDENCE_TREES = {
  Sentinel: {
    startPosition: TRANSCENDENCE_START_POSITION,
    nodes: [
      { position: '1:1', type: 'sigil', category: 'sigil', stats: [] },
      { position: '27:1', type: 'sigil', category: 'sigil', stats: [] },
      { position: '1:2', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '2:2', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '3:2', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '25:2', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '26:2', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '27:2', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '3:3', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '4:3', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '5:3', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '6:3', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '7:3', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '8:3', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '20:3', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '21:3', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '22:3', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '23:3', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '24:3', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '25:3', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '5:4', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '6:4', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '7:4', type: 'uncommon', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.8 }, { statKey: 'paralyze_chance', value: 0.4 }] },
      { position: '8:4', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '20:4', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '21:4', type: 'uncommon', category: 'offense', stats: [{ statKey: 'attack_pct', value: 1.6 }, { statKey: 'crit_mult', value: 2.8 }] },
      { position: '22:4', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '23:4', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '5:5', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '6:5', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '7:5', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '8:5', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '9:5', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '19:5', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '20:5', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '21:5', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '22:5', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '23:5', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '5:6', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '6:6', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '7:6', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '8:6', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '9:6', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '10:6', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '18:6', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '19:6', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '20:6', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '21:6', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '22:6', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '23:6', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '4:7', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '5:7', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '6:7', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '7:7', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '8:7', type: 'uncommon', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.8 }, { statKey: 'miss_chance', value: 1.6 }] },
      { position: '9:7', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '10:7', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '11:7', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '15:13', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '17:7', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '18:7', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '19:7', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '20:7', type: 'uncommon', category: 'offense', stats: [{ statKey: 'attack_pct', value: 1.6 }, { statKey: 'crit_mult', value: 2.8 }] },
      { position: '21:7', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '22:7', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '23:7', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '24:7', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '4:8', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '5:8', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '6:8', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '7:8', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '8:8', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '9:8', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '10:8', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '11:8', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '12:8', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '13:8', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '14:8', type: 'uncommon', category: 'defense', stats: [{ statKey: 'miss_chance', value: 1.6 }, { statKey: 'paralyze_chance', value: 0.4 }] },
      { position: '15:8', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '16:8', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '17:8', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '18:8', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '19:8', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '20:8', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '21:8', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '22:8', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '23:8', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '24:8', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '4:9', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '5:9', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '6:9', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '7:9', type: 'uncommon', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.8 }, { statKey: 'paralyze_chance', value: 0.4 }] },
      { position: '8:9', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '9:9', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '10:9', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '11:9', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '12:9', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '13:9', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '14:9', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '15:9', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '16:9', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '17:9', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '18:9', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '19:9', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '20:9', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '21:9', type: 'uncommon', category: 'offense', stats: [{ statKey: 'attack_pct', value: 1.6 }, { statKey: 'penetration', value: 2 }] },
      { position: '22:9', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '23:9', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '24:9', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '5:10', type: 'glyph', category: 'glyph', stats: [] },
      { position: '6:10', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '8:10', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '9:10', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '10:10', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '11:10', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '12:10', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '13:10', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '14:10', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '15:10', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '16:10', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '17:10', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '18:10', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '19:10', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '20:10', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '22:10', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '23:10', type: 'glyph', category: 'glyph', stats: [] },
      { position: '5:11', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '6:11', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '7:11', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '8:11', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '9:11', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '10:11', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '11:11', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '12:11', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '13:11', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '14:11', type: 'uncommon', category: 'offense', stats: [{ statKey: 'speed', value: 2 }, { statKey: 'miss_chance', value: 1.6 }] },
      { position: '15:11', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '16:11', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '17:11', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '18:11', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '19:11', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '20:11', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '21:11', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '22:11', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '23:11', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '5:12', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '6:12', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '8:12', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '9:12', type: 'glyph', category: 'glyph', stats: [] },
      { position: '10:12', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '13:12', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '14:12', type: 'glyph', category: 'glyph', stats: [] },
      { position: '15:12', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '18:12', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '19:12', type: 'glyph', category: 'glyph', stats: [] },
      { position: '20:12', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '22:12', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '23:12', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '5:13', type: 'glyph', category: 'glyph', stats: [] },
      { position: '6:13', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '8:13', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '9:13', type: 'uncommon', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.8 }, { statKey: 'miss_chance', value: 1.6 }] },
      { position: '10:13', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '11:13', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '12:13', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '13:13', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '14:13', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '16:13', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '17:13', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '18:13', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '19:13', type: 'uncommon', category: 'offense', stats: [{ statKey: 'crit_mult', value: 2.8 }, { statKey: 'crit', value: 0.8 }] },
      { position: '20:13', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '22:13', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '23:13', type: 'glyph', category: 'glyph', stats: [] },
      { position: '6:14', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '7:14', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '8:14', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '9:14', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '10:14', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '11:14', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '12:14', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '13:14', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '14:14', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '15:14', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '16:14', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '17:14', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '18:14', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '19:14', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '20:14', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '21:14', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '22:14', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '6:15', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '7:15', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '8:15', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '9:15', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '10:15', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '11:15', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '12:15', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '13:15', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '14:15', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '15:15', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '16:15', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '17:15', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '18:15', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '19:15', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '20:15', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '21:15', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '22:15', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '7:16', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '8:16', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '9:16', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '10:16', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '11:16', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '12:16', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '13:16', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '14:16', type: 'uncommon', category: 'offense', stats: [{ statKey: 'attack_pct', value: 1.6 }, { statKey: 'lifesteal', value: 1 }] },
      { position: '15:16', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '16:16', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '17:16', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '18:16', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '19:16', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '20:16', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '21:16', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '7:17', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '8:17', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '9:17', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '10:17', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '18:17', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '19:17', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '20:17', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '21:17', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '8:18', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '9:18', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '10:18', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '18:18', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '19:18', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '20:18', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '8:19', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '9:19', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '10:19', type: 'uncommon', category: 'offense', stats: [{ statKey: 'speed', value: 2 }, { statKey: 'blind_chance', value: 0.8 }] },
      { position: '11:19', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '17:19', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '18:19', type: 'uncommon', category: 'offense', stats: [{ statKey: 'speed', value: 2 }, { statKey: 'crit', value: 0.8 }] },
      { position: '19:19', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '20:19', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '9:20', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '10:20', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '11:20', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '12:20', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '16:20', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '17:20', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '18:20', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '19:20', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '10:21', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '11:21', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '12:21', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '13:21', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '14:21', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '15:21', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '16:21', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '17:21', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '18:21', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '11:22', type: 'common', category: 'defense', stats: [{ statKey: 'hp_regen', value: 0.6 }] },
      { position: '12:22', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
      { position: '13:22', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '14:22', type: 'common', category: 'offense', stats: [{ statKey: 'penetration', value: 1 }] },
      { position: '15:22', type: 'common', category: 'offense', stats: [{ statKey: 'lifesteal', value: 0.5 }] },
      { position: '16:22', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '17:22', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '12:23', type: 'common', category: 'defense', stats: [{ statKey: 'blind_chance', value: 0.4 }] },
      { position: '13:23', type: 'common', category: 'defense', stats: [{ statKey: 'paralyze_chance', value: 0.2 }] },
      { position: '14:23', type: 'uncommon', category: 'offense', stats: [{ statKey: 'attack_pct', value: 1.6 }, { statKey: 'speed', value: 2 }] },
      { position: '15:23', type: 'common', category: 'offense', stats: [{ statKey: 'crit', value: 0.4 }] },
      { position: '16:23', type: 'common', category: 'offense', stats: [{ statKey: 'crit_mult', value: 1.4 }] },
      { position: '13:24', type: 'common', category: 'defense', stats: [{ statKey: 'miss_chance', value: 0.8 }] },
      { position: '14:24', type: 'common', category: 'offense', stats: [{ statKey: 'attack_pct', value: 0.8 }] },
      { position: '15:24', type: 'common', category: 'offense', stats: [{ statKey: 'speed', value: 1 }] },
      { position: '14:25', type: 'common', category: 'defense', stats: [{ statKey: 'health_pct', value: 1 }] },
    ],
  },
  Warrior: null, // not yet transcribed
};
